add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

target("qu3e")
    set_kind("static")
    set_languages("c++11")
    add_files("src/**.cpp") 
    add_includedirs("src", {public = true})
    add_headerfiles("src/**.h", "src/**.inl")

target("qu3e_demo")
    set_kind("binary")
    set_languages("c++23")
    add_files("demo/**.cpp")
    add_includedirs("demo")
    add_deps("qu3e", "zabato_imgui", "zabato_sdl2", "zabato_gl", "cstd", "zabato")
